apiVersion: v1
kind: Service
metadata:
  name: po1-prometheus-operator-calico
  namespace: kube-system
  labels:
    app: prometheus-operator-calico
spec:
  selector:
    k8s-app: calico-node
  ports:
  - name: metrics
    port: 9091
    targetPort: 9091
