#!/bin/bash
kubectl -n monitoring create secret generic alertmanager \
	--from-literal=alertmanager.yaml="$(< alertmanager-secret.yaml)" \
	--dry-run -oyaml | kubectl -n monitoring replace secret --filename=-
