#!/bin/bash
kubectl -n kube-system create secret generic etcd-client-cert \
--from-file=/home/fritchie/tls/member-k8m01.pem \
--from-file=/home/fritchie/tls/member-k8m01-key.pem \
--from-file=/home/fritchie/tls/ca.pem
